### ISSUE TITLE
Testing out multi-item tracker

### ISSUE THREAD

**Issue by JeremiahClapfoot** [JeremiahClapfoot/discordintegration#9]
### Devbranch 4.20

- [x] Fix the shit
- [x] Do this too
- [x] If we have time
- [x] Nice to have
